server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # --- MFEs via reverse proxy (mismo ORIGIN => sin CORS) ---
  location /carrito/ {
    proxy_pass http://carrito/; #//aquí carrito Es un hostname dentro de la red Docker, que se corresponde con docker-compose.yml
  }#//GET http://carrito/remoteEntry.js carrito se resuelve vía DNS interno Docker apunta al contenedor del servicio carrito
  location /perfil/ {
    proxy_pass http://perfil/;
  }

  location /productos/ {
    proxy_pass http://productos/;
  }

  # --- Shell SPA ---
  location / {
    try_files $uri $uri/ /index.html;
  }
}

# server {
#   listen 80;
#   server_name _;

#   root /usr/share/nginx/html;
#   index index.html;

#   location / {
#     try_files $uri $uri/ /index.html;
#   }
# }